#!/bin/sh

# Colorize commands when possible.
# ls="ls -hN --color=auto --group-directories-first" \
alias \
    cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
    ls="lsd -h" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	cat="bat"


# Git aliases
alias \
    ga="git add" \
    gcm="git commit -m" \
    gp="git push" \
    gaa="git add ." \
    gs="git status" \
    gd="git diff" \
    gl="git log" \
    gb="git branch" \
    gcm="git commit -m"

# Change bad habits
alias \
    vim="nvim" \
    sudo="doas"

# system aliases
alias \
    suspend="systemctl suspend"

# Change bad habits
alias \
    cheat="curl cht.sh/"

alias \
    mail="mbsync -a && neomutt"

